name: DevOps Pipeline for FastAPI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
env:
  AZURE_CONTAINER_REGISTRY: "appbakdata"
  CONTAINER_NAME: "bakdata/fastapi-app-db"
  RESOURCE_GROUP: "bakdata-devops"
  CLUSTER_NAME: "bakdata-aks"
  DEPLOYMENT_MANIFEST_PATH: "manifests/deployment.yaml"
  
jobs:
  build:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Creating .env file
        run: |
          echo "DATABASE_URL=postgresql+asyncpg://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@postgres-service:5432/${{ secrets.POSTGRES_DB }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Build and push image to ACR
        run: |
          az acr build \
            --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }} \
            --registry ${{ env.AZURE_CONTAINER_REGISTRY }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            .
  update:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v2
      with:
        repository: sensgithub/DevOps-Project
        ref: 'main'
        token: ${{ secrets.GIT_TOKEN }}
      
    - name: Update deployment YAML file
      run: |
        git config --global user.email "svetlan.nikolov@proton.me"
        git config --global user.name "sensgithub"
        git clone https://sensgithub:${{ secrets.GIT_REPO_TOKEN }}@github.com/sensgithub/bakdata-task.git
        cd bakdata-task/manifests/
        sed -i "s#bakdata.*#bakdata/fastapi-app-db:${{ github.sha }}#g" deployment.yaml
        git add deployment.yml
        git commit -m "Updated Deployment Number: fastapi-app-db:${{ github.sha }}"
        git push origin main
        
  deploy:
    permissions:
      actions: read
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    needs: [update]
    steps:
      - uses: actions/checkout@v4
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: Set up kubelogin
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.25'
          
      - name: Get K8s context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}
          admin: 'false'
          use-kubelogin: 'true'
          
      - name: Deploy to AKS
        uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: ${{ env.DEPLOYMENT_MANIFEST_PATH }}
